if (process.env.NODE_ENV !== "production")
    require('dotenv').config()

export const config = {
    PORT : process.env.PORT,
    URL: process.env.FBCACHE_FIREBASE_URL,
    CREDENTIAL_TYPE: process.env.FBCACHE_FIREBASE_CREDENTIAL_TYPE,
    CREDENTIAL_FILE_TYPE: process.env.FBCACHE_FIREBASE_CREDENTIAL_FILE_TYPE,
    CREDENTIAL_FILE_PROYECT_ID: process.env.FBCACHE_FIREBASE_CREDENTIAL_FILE_PROYECT_ID,
    CREDENTIAL_FILE_PRIVATE_KEY_ID: process.env.FBCACHE_FIREBASE_CREDENTIAL_FILE_PRIVATE_KEY_ID,
    CREDENTIAL_FILE_PRIVATE_KEY: process.env.FBCACHE_FIREBASE_CREDENTIAL_FILE_PRIVATE_KEY,
    CREDENTIAL_FILE_CLIENT_EMAIL: process.env.FBCACHE_FIREBASE_CREDENTIAL_FILE_CLIENT_EMAIL,
    CREDENTIAL_FILE_CLIENT_ID: process.env.FBCACHE_FIREBASE_CREDENTIAL_FILE_CLIENT_ID,
    CREDENTIAL_FILE_AUTH_URI: process.env.FBCACHE_FIREBASE_CREDENTIAL_FILE_AUTH_URI,
    CREDENTIAL_FILE_TOKEN_URI: process.env.FBCACHE_FIREBASE_CREDENTIAL_FILE_TOKEN_URI,
    CREDENTIAL_FILE_AUTH_PROV_CERT: process.env.FBCACHE_FIREBASE_CREDENTIAL_FILE_AUTH_PROV_CERT,
    CREDENTIAL_FILE_CLIENT_CERT: process.env.FBCACHE_FIREBASE_CREDENTIAL_FILE_CLIENT_CERT,
    CONFIG: process.env.CONFIG,
    CONFIG_LOCATION: process.env.CONFIG_LOCATION,
    NODE_ENV: process.env.NODE_ENV
}